2021-11-29-report.org
Ada being a name should be spelled Ada, not ADA :)
=> Minor typo

2021-11-monthly-report.org
This is the report and changelog for November in the GCC Rust project.
=> Monthly Report for November

2022-03-04-community-call.md, 2022-03-07-report.org
This also contains the community call meeting notes from the 4th March 2022
=> Add weekly report for 28th Feb to 7th March 2022

2022-03-monthly-report.org, 2022-04-01-community-call.md
=> Add monthly report for march 2022

2022-06-13-report.org
[Rendered](https://github.com/Rust-GCC/Reporting/blob/weekly-2022-06-13/2022-06-13-report.org)
=> 2022-06-13: Add weekly report

2022-06-monthly-report.org
If anyone wants to add to the `Detailed changelog` section, please feel free!
=> 2022-06: Add monthly report

2022-08-29-report.org
@abbasfaisal Feel free to review and ask for changes on the bit about the constant evaluation :)
=> 2022-08-29: Add weekly report

2022-10-17-report.org
Change the day to 17 instead of changing the month. Also adjust the date in the header.
=> Update and rename 2022-17-10-report.org to 2022-10-17-report.org

2022-10-31-report.org
This is a copy paste of this week's report, with the risk table modified :)
=> 2022-10-31: Add template for report

2022-10-monthly-report.org
Detailed changelog incoming :) If anyone has anything they'd like to put in there, feel free to!
=> 2022-10-monthly: Add base for monthly report

2023-04-17-report.org
Last week was a bit slower than usual, so the report is quite tiny. Not sure if anyone has detailed technical stuff they'd like to add at the end but feel free :)
=> 2023-04-17-report: Add base for report

2023-04-24-report.org
@philberty @P-E-P feel free to add directly to the Detailed Changelog section if you have anything you'd like to talk about :)
=> 2023-04-24-report: Add base for report

2023-05-monthly-report.org
@philberty @P-E-P if you'd like to add a detailed changelog I think it would be nice :) I'll spend some time writing some for derive macros
=> 2023-05-monthly-report: Add base report

2023-01-30-report.org, 2023-02-20-report.org, 2023-02-27-report.org, 2023-02-monthly-report.org, 2023-03-06-report.org, 2023-03-20-report.org, 2023-03-27-report.org, 2023-03-monthly-report.org, 2023-04-11-report.org, 2023-04-17-report.org, 2023-04-24-report.org, 2023-05-15-report.org, 2023-05-22-report.org
Really sorry again @powerboat9
=> reports: Fix @powerboat9's displayed name

2023-06-12-report.org, 2023-06-19-report.org
- 2023-06-12-report: Fix date
- 2023-06-19-report: Add base for report
=> 2023-06-19: Add weekly report

2023-07-monthly-report.org
@philberty @P-E-P: do you have something you would like to talk about in the Detailed Changelog section?
@tamaroning @mahadmuhammad: ping for review :)
=> 2023-07-monthly-report: Add base report

2023-08-07-report.org
I'm not used to data collection from issues/milestone. I'll investigate further to collect issues/task completion during the past week. In the meantime, most of it is here and can be reviewed.
=> 2023-08-07: Add weekly report

2023-09-18-report.org
=> 2023-09-18 Add weekly report

2023-09-25-report.org
Add the report for the past week.
=> 2023-09-25: Add weekly report.

2023-10-30-report.org
=> 2023-10-30-report: Add weekly report

2024-02-26-report.org
- 2024-02-19: Add weekly report
- 2024-02-26: Add report
=> 2024 02 26 report

2024-03-monthly-report.org, 2024-04-15-report.org
- 2024-04-15: Add report
- 2024-03-monthly: Fix contributor list
=> 2024-04-15: Add weekly report

2024/2024-07-monthly-report.org
=> 2024-07: Add monthly report

2024/2024-10-14-report.org
Bugs/Task have been taken from 2024/09/23 and may be inaccurate, I can't find any newer PR with accurate numbers. I'll update deltas and previous week number later.
=> 2024-10-14: Add weekly report

2024/2024-11-18-report.org
- 2024/11-18: Add base for weekly report
- 2024/11-18: Finish report
=> 2024/11-18: Add weekly report

2024/2024-11-monthly-report.org, 2024/2024-12-09-report.org
- **2024/12-09: Add base for weekly report**
- **2024/11-monthly: Fix formatting**
- **2024/12-09: Finish weekly report**
=> 2024/12-09: Add weekly report
